/* Generated by AN DISI Unibo */ 
package it.unibo.parkmanagerservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkmanagerservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						forward("trolleycmd", "trolleycmd(moveToIn)" ,"trolley" ) 
						forward("trolleycmd", "trolleycmd(moveToHome)" ,"trolley" ) 
						delay(6200) 
						forward("trolleycmd", "trolleycmd(moveToSlotIn)" ,"trolley" ) 
						forward("trolleycmd", "trolleycmd(moveToHome)" ,"trolley" ) 
						delay(5000) 
						forward("trolleycmd", "trolleycmd(moveToSlotOut)" ,"trolley" ) 
						forward("trolleycmd", "trolleycmd(moveToOut)" ,"trolley" ) 
						forward("trolleycmd", "trolleycmd(end)" ,"trolley" ) 
					}
				}	 
			}
		}
}
