/* Generated by AN DISI Unibo */ 
package it.unibo.thermometer

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Thermometer ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var fan = 0 
				
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("thermometer | starting ")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("thermometer | work")
					}
					 transition(edgeName="t00",targetState="handleMsg",cond=whenEvent("temp"))
				}	 
				state("handleMsg") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("temp(V)"), Term.createTerm("temp(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var T= payloadArg(0) 
								println("thermometer | work $T")
								forward("temperature", "temperature($T)" ,"parkingmanager" ) 
								println("$name in ${currentState.stateName} | $currentMsg")
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
