/* Generated by AN DISI Unibo */ 
package it.unibo.prova

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Prova ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var weightValue ="antonio" 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = true
						println("prova | start")
					}
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("working") { //this:State
					action { //it:State
						println("prova : working")
						delay(5000) 
					}
					 transition( edgeName="goto",targetState="readmessage", cond=doswitch() )
				}	 
				state("readmessage") { //this:State
					action { //it:State
						delay(5000) 
						println("prova : readMessage")
						weightValue = utility.HandleData().getState("weightsensor") 
						println(weightValue)
					}
				}	 
			}
		}
}
