/* Generated by AN DISI Unibo */ 
package it.unibo.parkmanagerservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkmanagerservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 	var SLOTNUM = 0
				var CARSLOTNUM = 0 
				var TOKENID = " "
				var INFREE = 1   
				var OUTFREE = 1
				var stateTrolley =""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("parkmanagerservice | start")
					}
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("working") { //this:State
					action { //it:State
						println("parkmanagerservice | working")
						println("parkmanagerservice [working] | OUTDOOR = $OUTFREE")
						stateTrolley = utility.HandleData().getState("trolley") 
					}
					 transition(edgeName="t012",targetState="acceptIn",cond=whenRequest("notifyIn"))
					transition(edgeName="t013",targetState="acceptOut",cond=whenRequest("pickup"))
					transition(edgeName="t014",targetState="carenter",cond=whenRequest("carenter"))
					transition(edgeName="t015",targetState="handlemsgIn",cond=whenEvent("weightsensor"))
					transition(edgeName="t016",targetState="handlemsgOut",cond=whenDispatch("outfree"))
					transition(edgeName="t017",targetState="theend",cond=whenDispatch("end"))
				}	 
				state("handlemsgIn") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("weightsensor(W)"), Term.createTerm("weightsensor(W)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var W = payloadArg(0).toInt()  
								if( W>0 
								 ){INFREE = 0  
								println("parkManagerService [handlemsgIn] | INDOOR occupied")
								}
								else
								 {INFREE = 1 
								 println("parkManagerService [handlemsgIn] | INDOOR free")
								 }
						}
					}
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("handlemsgOut") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("outfree(free)"), Term.createTerm("outfree(W)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var O = payloadArg(0)  
								if( O.equals("occ") 
								 ){OUTFREE = 0  
								println("parkManagerService [handlemsgOut] | OUTDOOR occupied")
								}
								if( O.equals("free") 
								 ){OUTFREE = 1 
								println("parkManagerService [handlemsgOut] | OUTDOOR free")
								}
						}
					}
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("acceptIn") { //this:State
					action { //it:State
						println("parkManagerService | acceptIn")
						if( checkMsgContent( Term.createTerm("notifyIn(N)"), Term.createTerm("notifyIn(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  INFREE ==1 &&  !stateTrolley.equals("trolley(stopped)") 
								 ){ SLOTNUM = Slotnum.getSlotnum()  
								answer("notifyIn", "informIn", "informIn($SLOTNUM)"   )  
								Slotnum.uptadeSlotnum(SLOTNUM, false) 
								}
								else
								 {println("parkManagerService [acceptIn] | indoor-area occupied, the request could not be processed")
								 }
						}
					}
					 transition(edgeName="t018",targetState="carenter",cond=whenRequest("carenter"))
					transition(edgeName="t019",targetState="acceptOut",cond=whenRequest("pickup"))
					transition(edgeName="t020",targetState="acceptIn",cond=whenRequest("notifyIn"))
					transition(edgeName="t021",targetState="handlemsgIn",cond=whenEvent("weightsensor"))
					transition(edgeName="t022",targetState="handlemsgOut",cond=whenDispatch("outfree"))
					transition(edgeName="t023",targetState="theend",cond=whenDispatch("end"))
				}	 
				state("carenter") { //this:State
					action { //it:State
						println("parkManagerService | caraenter")
						if( checkMsgContent( Term.createTerm("carenter(C)"), Term.createTerm("carenter(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 SLOTNUM= payloadArg(0).toInt()  
								if(  SLOTNUM!= 0 && INFREE == 1 
								 ){forward("trolleycmd", "trolleycmd(moveToIn)" ,"trolley" ) 
								 var MOVETOSLOT = "moveToSlot".plus(SLOTNUM)  
								println("parkManagerService [carenter] | send to trolley $MOVETOSLOT")
								forward("trolleycmd", "trolleycmd($MOVETOSLOT)" ,"trolley" ) 
								 TOKENID=  Slotnum.generateTOKENID(SLOTNUM)  
								println("parkManagerService [carenter] | send to client TOOKENID = $TOKENID")
								answer("carenter", "receipt", "receipt($TOKENID)"   )  
								}
								else
								 {println("parkManagerService [carenter] | send to trolley moveToHome")
								 forward("trolleycmd", "trolleycmd(moveToHome)" ,"trolley" ) 
								 answer("carenter", "receipt", "receipt(no)"   )  
								 Slotnum.uptadeSlotnum(SLOTNUM, true) 
								 }
						}
					}
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("acceptOut") { //this:State
					action { //it:State
						stateTrolley = utility.HandleData().getState("trolley") 
						println("parkManagerService | acceptOut ")
						if( checkMsgContent( Term.createTerm("pickup(TOKENID)"), Term.createTerm("pickup(TOKENID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if( OUTFREE == 1 &&   !stateTrolley.equals("trolley(stopped)") 
								 ){TOKENID= payloadArg(0).toString()  
								println("parkManagerService [acceptOut] | receive TOKENID = $TOKENID")
								 CARSLOTNUM = Slotnum.findSlot(TOKENID)  
								println("parkManagerService [acceptOut] | receive CARSLOTNUM = $CARSLOTNUM")
								answer("pickup", "ok", "ok(1)"   )  
								println("parkManagerService [acceptOut] | receive OUTFREE = $OUTFREE")
								 Slotnum.uptadeSlotnum(CARSLOTNUM, true)
												var MOVETOSLOT = "moveToSlot".plus(CARSLOTNUM)  
								forward("trolleycmd", "trolleycmd($MOVETOSLOT)" ,"trolley" ) 
								forward("trolleycmd", "trolleycmd(moveToOut)" ,"trolley" ) 
								delay(600) 
								}
								else
								 {answer("pickup", "ok", "ok(0)"   )  
								 println("parkManagerService [acceptOut]: outdoor-area occupied, the request could not be processed")
								 }
						}
					}
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("theend") { //this:State
					action { //it:State
						forward("trolleycmd", "trolleycmd(end)" ,"trolley" ) 
					}
				}	 
			}
		}
}
