/* Generated by AN DISI Unibo */ 
package it.unibo.parkingmanager

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkingmanager ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var fanIsStarted = 0
			  var robotIsActive = 1 
			  var stateTrolley = ""
			  var stateFan= ""
			  var start =  0L
			  var differenza = 0L
			  var temp1 = 0 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("parkingmanager | start")
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						println("parkingmanager | waiting")
					}
					 transition(edgeName="t027",targetState="handleTemperature",cond=whenEvent("temperature"))
					transition(edgeName="t028",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleTemperature") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("temperature(T)"), Term.createTerm("temperature(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  temp1= payloadArg(0).toInt()
												stateTrolley = utility.HandleData().getState("trolley")
												stateFan = utility.HandleData().getState("fan")
								println("parkingmanager [handleTemperature] | state trolley = $stateTrolley state fan = $stateFan ")
								println("parkingmanager [handleTemperature] | temperature = $temp1 ")
								if(  temp1 > 35 
								 ){forward("warning", "warning(TempOverMax)" ,"parkservicestatusgui" ) 
								}
								else
								 {forward("warning", "warning(TempUnderMax)" ,"parkservicestatusgui" ) 
								 }
						}
						stateTimer = TimerActor("timer_handleTemperature", 
							scope, context!!, "local_tout_parkingmanager_handleTemperature", 2000.toLong() )
					}
					 transition(edgeName="t029",targetState="autoFan",cond=whenTimeout("local_tout_parkingmanager_handleTemperature"))   
					transition(edgeName="t030",targetState="handleTemperature",cond=whenEvent("temperature"))
					transition(edgeName="t031",targetState="handleTrolley",cond=whenEvent("stateChangetrolley"))
					transition(edgeName="t032",targetState="handleFan",cond=whenEvent("stateChangefan"))
					transition(edgeName="t033",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleTrolley") { //this:State
					action { //it:State
						println("parkingmanager | handleTemperature troll = $temp1 ")
						if( checkMsgContent( Term.createTerm("stateChangetrolley(V)"), Term.createTerm("stateChangetrolley(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								var stateT= payloadArg(0) 
								if(  temp1 > 35 && !stateTrolley.equals("trolley(stopped)") && stateT.equals("stop") 
								 ){println("parkingmanager | trolley stopped ")
								forward("trolleystop", "trolleystop(V)" ,"trolley" ) 
								}
								if(  temp1 < 35  &&  stateTrolley.equals("trolley(stopped)") && stateT.equals("work") 
								 ){println("parkingmanager | trolley working ")
								forward("trolleyresume", "trolleyresume(V)" ,"trolley" ) 
								}
						}
						stateTimer = TimerActor("timer_handleTrolley", 
							scope, context!!, "local_tout_parkingmanager_handleTrolley", 2000.toLong() )
					}
					 transition(edgeName="t034",targetState="autoFan",cond=whenTimeout("local_tout_parkingmanager_handleTrolley"))   
					transition(edgeName="t035",targetState="handleTemperature",cond=whenEvent("temperature"))
					transition(edgeName="t036",targetState="handleFan",cond=whenEvent("stateChangefan"))
					transition(edgeName="t037",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleFan") { //this:State
					action { //it:State
						println("parkingmanager [handleFan] | temperature = $temp1 ")
						if( checkMsgContent( Term.createTerm("stateChangefan(V)"), Term.createTerm("stateChangefan(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								var stateF= payloadArg(0) 
								if(  temp1 > 35  && stateFan.equals("fan(stop)") && stateFan.equals("stop") 
								 ){println("parkingmanager [handleFan] | fan working ")
								forward("fanstart", "fanstart(V)" ,"fan" ) 
								}
								if(  temp1 < 35  && stateFan.equals("fan(work)") && stateFan.equals("work")  
								 ){println("parkingmanager [handleFan] | fan stopped ")
								forward("fanstop", "fanstop(off)" ,"fan" ) 
								}
						}
					}
					 transition(edgeName="t038",targetState="handleTemperature",cond=whenEvent("temperature"))
					transition(edgeName="t039",targetState="handleTrolley",cond=whenEvent("stateChangetrolley"))
					transition(edgeName="t040",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("autoFan") { //this:State
					action { //it:State
						if(  temp1 > 35  && stateFan.equals("fan(stop)") 
						 ){println("parkingmanager [autoFan] | fan working ")
						forward("fanstart", "fanstart(V)" ,"fan" ) 
						}
						if(  temp1 < 35  && stateFan.equals("fan(work)")   
						 ){println("parkingmanager [autoFan] | fan stopped ")
						forward("fanstop", "fanstop(V)" ,"fan" ) 
						}
					}
					 transition(edgeName="t041",targetState="handleTemperature",cond=whenEvent("temperature"))
					transition(edgeName="t042",targetState="handleTrolley",cond=whenEvent("stateChangetrolley"))
					transition(edgeName="t043",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleAlarm") { //this:State
					action { //it:State
						println("parkingmanager [handleAlarm] |  OVER DTFREE TIME")
						emit("alarm", "alarm(V)" ) 
						stateTimer = TimerActor("timer_handleAlarm", 
							scope, context!!, "local_tout_parkingmanager_handleAlarm", 1000.toLong() )
					}
					 transition(edgeName="t044",targetState="autoFan",cond=whenTimeout("local_tout_parkingmanager_handleAlarm"))   
					transition(edgeName="t045",targetState="handleTemperature",cond=whenEvent("temperature"))
					transition(edgeName="t046",targetState="handleTrolley",cond=whenEvent("stateChangetrolley"))
					transition(edgeName="t047",targetState="handleFan",cond=whenEvent("stateChangefan"))
					transition(edgeName="t048",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
			}
		}
}
