/* Generated by AN DISI Unibo */ 
package it.unibo.parkingmanager

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkingmanager ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var fanIsStarted = 0 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("parkingManager | start")
					}
					 transition(edgeName="t02",targetState="handleTemp",cond=whenEvent("temperature"))
				}	 
				state("handleTemp") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("temperature(T)"), Term.createTerm("temperature(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var temp= payloadArg(0).toInt() 
								if(  temp > 35 && fanIsStarted == 0 
								 ){println("ParkingManager: temp > 35, invio il comando di accensione al fan ")
								forward("fanstart", "fanstart(on)" ,"fan" ) 
								}
								if(  temp <= 35 && fanIsStarted == 1 
								 ){println("ParkingManager: temp < 30, invio il comando di stop al fan")
								forward("fanstop", "fanstop(off)" ,"fan" ) 
								}
						}
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
